export const SET_WORKOUT = 'SET_WORKOUT';
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT';
export const EDIT_WORKOUT = 'EDIT_WORKOUT';
export const WORKOUT_ACTIVE_STATUS = 'WORKOUT_ACTIVE_STATUS';
export const UPDATE_ROUTINE_TRACKER = 'UPDATE_ROUTINE_TRACKER';
export const MARK_AS_FINISH = 'MARK_AS_FINISH';
export const RESET_WORKOUT = 'RESET_WORKOUT';
export const REPETITON_STATUS = 'REPETITON_STATUS';
export const WORKOUT_UPLOADED = 'WORKOUT_UPLOADED';

export const ADD_ROUTINE = 'ADD_ROUTINE';
export const MARK_AS_DONE = 'MARK_AS_DONE';

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_USER = 'SET_USER';

export const SET_PUBLIC_WORKOUT = 'SET_PUBLIC_WORKOUT';

export const SET_PHYSICAL_DATA = 'SET_PHYSICAL_DATA';
